// EarlyAlertAI dashboard
// Reads two static files generated by the Python pipeline:
//   - risk_scores.json   (per-student risk scores + SHAP top reasons)
//   - model_metrics.json (accuracy / precision / recall / F1 / ROC-AUC)
//
// When real LMS/attendance/CA data becomes available, these two files
// simply get regenerated by model/train_model.py — nothing here needs
// to change as long as the JSON shape stays the same.

let allStudents = [];
let currentFaculties = new Set();
let currentYears = new Set();

const els = {
  searchInput: document.getElementById("searchInput"),
  facultyFilter: document.getElementById("facultyFilter"),
  yearFilter: document.getElementById("yearFilter"),
  tierChecks: document.querySelectorAll('.field--tiers input[type="checkbox"]'),
  rosterBody: document.getElementById("rosterBody"),
  rosterCount: document.getElementById("rosterCount"),
  statTotal: document.getElementById("statTotal"),
  statHigh: document.getElementById("statHigh"),
  statModerate: document.getElementById("statModerate"),
  statLow: document.getElementById("statLow"),
  metricsList: document.getElementById("metricsList"),
  drawer: document.getElementById("drawer"),
  drawerContent: document.getElementById("drawerContent"),
  drawerClose: document.getElementById("drawerClose"),
  scrim: document.getElementById("scrim"),
};

async function init() {
  try {
    const [riskRes, metricsRes] = await Promise.all([
      fetch("risk_scores.json"),
      fetch("model_metrics.json"),
    ]);
    const riskData = await riskRes.json();
    const metrics = await metricsRes.json();

    allStudents = riskData.students;
    populateFilterOptions(allStudents);
    renderMetrics(metrics);
    renderSummary(riskData.counts, riskData.total_students);
    renderRoster(allStudents);
  } catch (err) {
    els.rosterBody.innerHTML =
      '<tr><td colspan="5" style="padding:1.5rem;color:var(--paper-dim)">' +
      "Could not load risk_scores.json / model_metrics.json. Run model/train_model.py first, " +
      "then serve this dashboard folder over HTTP (not file://)." +
      "</td></tr>";
    console.error(err);
  }
}

function populateFilterOptions(students) {
  const faculties = [...new Set(students.map((s) => s.faculty))].sort();
  const years = [...new Set(students.map((s) => s.year_of_study))].sort();

  faculties.forEach((f) => {
    const opt = document.createElement("option");
    opt.value = f;
    opt.textContent = f;
    els.facultyFilter.appendChild(opt);
  });

  years.forEach((y) => {
    const opt = document.createElement("option");
    opt.value = y;
    opt.textContent = `Year ${y}`;
    els.yearFilter.appendChild(opt);
  });
}

function renderMetrics(metrics) {
  const rows = [
    ["Accuracy", metrics.accuracy],
    ["F1 (macro)", metrics.f1_macro],
    ["ROC-AUC (macro)", metrics.roc_auc_macro_ovr],
    ["5-fold CV acc.", metrics.cv_accuracy_5fold_mean],
  ];
  els.metricsList.innerHTML = rows
    .map(([label, val]) => `<dt>${label}</dt><dd>${val}</dd>`)
    .join("");
}

function renderSummary(counts, total) {
  els.statTotal.textContent = total;
  els.statHigh.textContent = counts.high;
  els.statModerate.textContent = counts.moderate;
  els.statLow.textContent = counts.low;
}

function getActiveTiers() {
  return [...els.tierChecks].filter((c) => c.checked).map((c) => c.value);
}

function applyFilters() {
  const query = els.searchInput.value.trim().toLowerCase();
  const faculty = els.facultyFilter.value;
  const year = els.yearFilter.value;
  const activeTiers = getActiveTiers();

  const filtered = allStudents.filter((s) => {
    if (query && !s.student_id.toLowerCase().includes(query)) return false;
    if (faculty !== "all" && s.faculty !== faculty) return false;
    if (year !== "all" && String(s.year_of_study) !== year) return false;
    if (!activeTiers.includes(s.risk_tier)) return false;
    return true;
  });

  renderRoster(filtered);
}

function renderRoster(students) {
  els.rosterCount.textContent = `${students.length} shown`;

  if (students.length === 0) {
    els.rosterBody.innerHTML =
      '<tr><td colspan="5" style="padding:1.5rem;color:var(--paper-dim)">No students match these filters.</td></tr>';
    return;
  }

  els.rosterBody.innerHTML = students
    .map(
      (s) => `
    <tr data-id="${s.student_id}">
      <td class="student-id">${s.student_id}</td>
      <td>${s.faculty}</td>
      <td>${s.year_of_study}</td>
      <td>
        <div class="score-bar-wrap">
          <div class="score-bar">
            <div class="score-bar__fill" style="width:${s.risk_score}%; background:var(--risk-${s.risk_tier})"></div>
          </div>
          <span class="score-value">${s.risk_score.toFixed(0)}</span>
        </div>
      </td>
      <td><span class="tier-badge tier-badge--${s.risk_tier}">${capitalize(s.risk_tier)}</span></td>
    </tr>
  `
    )
    .join("");

  [...els.rosterBody.querySelectorAll("tr[data-id]")].forEach((row) => {
    row.addEventListener("click", () => openDrawer(row.dataset.id));
  });
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function openDrawer(studentId) {
  const s = allStudents.find((x) => x.student_id === studentId);
  if (!s) return;

  const reasonsHtml = s.top_reasons
    .map((r) => {
      const cls = r.impact >= 0 ? "positive" : "negative";
      const sign = r.impact >= 0 ? "+" : "";
      return `
      <div class="reason-row">
        <span>${r.feature} <span style="color:var(--paper-dim)">(${r.value})</span></span>
        <span class="reason-impact ${cls}">${sign}${r.impact.toFixed(3)}</span>
      </div>`;
    })
    .join("");

  els.drawerContent.innerHTML = `
    <h2>${s.student_id}</h2>
    <p class="drawer__sub">${s.faculty} · Year ${s.year_of_study}</p>

    <div class="drawer__score">
      <span class="drawer__score-number" style="color:var(--risk-${s.risk_tier})">${s.risk_score.toFixed(0)}</span>
      <span class="tier-badge tier-badge--${s.risk_tier}">${capitalize(s.risk_tier)} risk</span>
    </div>

    <h3>Behavioral &amp; academic indicators</h3>
    <div class="metric-grid">
      <div><span class="metric-label">Attendance decline</span><span class="metric-value">${s.attendance_decline_pct}%</span></div>
      <div><span class="metric-label">LMS inactivity gap</span><span class="metric-value">${s.lms_inactivity_gap_days} days</span></div>
      <div><span class="metric-label">Assignment delay index</span><span class="metric-value">${s.assignment_delay_index}</span></div>
      <div><span class="metric-label">Grade volatility</span><span class="metric-value">${s.grade_volatility_score}</span></div>
      <div><span class="metric-label">Current average mark</span><span class="metric-value">${s.current_avg_mark}</span></div>
    </div>

    <h3>Why this score (SHAP top factors)</h3>
    ${reasonsHtml}
  `;

  els.drawer.classList.add("open");
  els.drawer.setAttribute("aria-hidden", "false");
  els.scrim.classList.add("open");
}

function closeDrawer() {
  els.drawer.classList.remove("open");
  els.drawer.setAttribute("aria-hidden", "true");
  els.scrim.classList.remove("open");
}

els.searchInput.addEventListener("input", applyFilters);
els.facultyFilter.addEventListener("change", applyFilters);
els.yearFilter.addEventListener("change", applyFilters);
els.tierChecks.forEach((c) => c.addEventListener("change", applyFilters));
els.drawerClose.addEventListener("click", closeDrawer);
els.scrim.addEventListener("click", closeDrawer);

init();
